### ISSUE TITLE
Tutorial is missing example how to connect to simple Modbus Device.

### ISSUE THREAD

**Issue by openlisp** [parallelbgls/Modbus.Net#1]
Simple Modbus libraries usually offer very simple methods offering TCP communication with reading and writing coils i.e. : 
void setCoils(int offset, bool [] data); 
bool [] readCoils(int offset, int number) ;

How to achieve this with your library. This is somethig what is definetely missing in your Tutorial.

**Comment by parallelbgls** [comment]
First of all sorry for waiting in long time. I am writing unit tests currently. After that I will write a complete tutorial for all implemented protocols. This should be completed in one month.

**Comment by openlisp** [comment]
Great news. Thank you for your reply. In that case I'm looking to the end of the month.

**Comment by parallelbgls** [comment]
Alright, I don't have any wired network in my hometown so I need to answer you in this comment.

Coil in Modbus.Net is "0X", so you can set your AddressUnit like

var addressUnit = new AddressUnit
{
Area="0X",
Address=1,
DataType=typeof(bool),
};

And you can use this addressUnit to get Modbus address 00001 using GetData/SetData
