### ISSUE TITLE
怎么设置串口的波特率  ？

### ISSUE THREAD

**Issue by lihongfang16** [parallelbgls/Modbus.Net#12]

**Comment by parallelbgls** [comment]
#10

**Comment by parallelbgls** [comment]
当前dev通道已设置了临时的更换波特率的参数，但是所有串口波特率必须相同。1.4.0正式版会变更为不同串口可设置不同的波特率。

**Comment by parallelbgls** [comment]
dev通道相应的开发已完成，但是串口没有环境无法测试，当前issue关闭，但是任何发现错误的人可以继续提交issue在后面或重新提交issue。
