### ISSUE TITLE
What is the license on this?

### ISSUE THREAD

**Issue by StingyJack** [parallelbgls/Modbus.Net#13]
MIT, GPL, APL, etc....

**Comment by sebandraos** [comment]
A bit late for a genuine reply but worth having a response here anyway:
At the time of writing this is licensed with an [MIT License](https://choosealicense.com/licenses/mit/) according to the [LICENSE ](https://github.com/parallelbgls/Modbus.Net/blob/master/LICENSE) file.

**Comment by parallelbgls** [comment]
Package has been assigned to MIT. Close.
