### ISSUE TITLE
西门子的modbus和其他modbus有什么区别么？

### ISSUE THREAD

**Issue by cuihee** [parallelbgls/Modbus.Net#14]
我看到wiki里面

> Modbus.Net是框架的主体。
> Modbus.Net.Standard是框架主体的.NET Standard实现。
> Modbus.Net.Modbus是Modbus.Net的Modbus协议实现。
> Modbus.Net.Siemens是Modbus.Net的西门子协议实现。
> Modbus.Net.OPC是Modbus.Net的OPC实现。

这是不是说明西门子的modbus和其他的modbus不太一样？

**Comment by parallelbgls** [comment]
如果您挂了Modbus模块请用Modbus.Net.Modbus
