### ISSUE TITLE
Custom Modbus function

### ISSUE THREAD

**Issue by djl-85** [parallelbgls/Modbus.Net#15]
Hello, It would be nice if you provide a guide in order to explain how to develop custom Modbus functions. Could it be possible?

Thanks in advance.

**Comment by parallelbgls** [comment]
[https://github.com/parallelbgls/Modbus.Net/wiki/3-Using-Modbus.Net-to-implement-a-protocol](https://github.com/parallelbgls/Modbus.Net/wiki/3-Using-Modbus.Net-to-implement-a-protocol)

**Comment by parallelbgls** [comment]
By the way, Modbus.Net don't use any internal class and basiclly use protected classes and functions for easy extensions. You can extend any Mobdus method you want. Try to read wiki and Modbus.Net.Modbus for more. If you have any problem, you can ask questions here.

**Comment by parallelbgls** [comment]
To see some examples, you can find the codes related by GetTime and SetTime function in Modbus.Net.Modbus. It is a custom Modbus Function implementation.
