### ISSUE TITLE
Does it support modbus-tcp

### ISSUE THREAD

**Issue by caneserr** [parallelbgls/Modbus.Net#19]
Any info ,this library supports modbus tcp? All the functionality? Some documentation or maybe a readme file would be helpful.

**Comment by parallelbgls** [comment]
Try to reference wiki for more informations.
[https://github.com/parallelbgls/Modbus.Net/wiki/4-Using-Modbus.Net](https://github.com/parallelbgls/Modbus.Net/wiki/4-Using-Modbus.Net)
