### ISSUE TITLE
s7 300连接读取数据失败，无任何反应。

### ISSUE THREAD

**Issue by neuhawk** [parallelbgls/Modbus.Net#3]
`     _siemensTcpMachine = new SiemensMachine(SiemensType.Tcp, "192.168.10.228", SiemensMachineModel.S7_300, null, true, 2, 0);

 var addresses = new List<AddressUnit>
            {
                new AddressUnit
                {
                    Id = "0",
                    Area = "M",
                    Address = 0,
                    SubAddress = 0,
                    CommunicationTag = "A1",
                    DataType = typeof(bool)
                }
            };

            _siemensTcpMachine.GetAddresses = addresses;

  var ans = await _siemensTcpMachine.GetDatasAsync(MachineGetDataType.Address);

`
读取数据一直长时间无响应。用sharp7是可以的。

**Comment by parallelbgls** [comment]
我刚才在本地搭了一个S7-300的环境测试是通过的，所以如果可能的话能不能安装一个wireshark把报文发给我看一下。

**Comment by parallelbgls** [comment]
我刚才发现了一个问题，你的List加了模板吗？

**Comment by neuhawk** [comment]
需要加什么模板?我从demo哪里测试改的阿.

**Comment by neuhawk** [comment]
刚才试了,调用 _siemensTcpMachine.Connect()超时

**Comment by parallelbgls** [comment]
应该是List\<AddressUnit\>而不是List，不知道您的代码是不是这样的。

另外Log系统未来会加上，但是现在没有，西门子的Connect超时有很多原因，比如连接码（就是那5个参数）有问题，还有TCP连接通讯不上。因为我的手上设备很少，不能排查所有的情况，所以我建议您用wireshark手动检查一下CreateReference的时候产生的通讯包是否被PLC拒绝。

**Comment by neuhawk** [comment]
好的,出差回来试用wireshark一下,谢谢了.

**Comment by parallelbgls** [comment]
1.3.8测试版已发布，请使用Serilog设置MinimumLevel为Verbose，查看所有通讯报文。
