### ISSUE TITLE
联系方式

### ISSUE THREAD

**Issue by aone** [parallelbgls/Modbus.Net#4]
你好，可否留联系方式？QQ或微信都可以的。

**Comment by parallelbgls** [comment]
先把必要的情况先扔到我的邮箱可以吗，一些敏感信息请通过邮箱交流，parallelbgls@outlook.com。

**Comment by parallelbgls** [comment]
另外请同时CC到parallelbgls@163.com中。

**Comment by parallelbgls** [comment]
QQ群已建立，关闭
