### ISSUE TITLE
netstandard support

### ISSUE THREAD

**Issue by dansiegel** [parallelbgls/Modbus.Net#8]
according to your readme you currently [netstandard2.0](https://github.com/parallelbgls/Modbus.Net#platform-supported) is a supported platform in [v1.3.10](https://github.com/parallelbgls/Modbus.Net#version-1310), but from the looks of your [csproj](https://github.com/parallelbgls/Modbus.Net/blob/master/Modbus.Net/Modbus.Net/Modbus.Net.csproj#L4) & your nuget's you're only shipping net45

**Comment by parallelbgls** [comment]
Please download Modbus.Net.Core
