### ISSUE TITLE
群主,这里异步需要加一个lock吧...

### ISSUE THREAD

**Issue by pigwing** [parallelbgls/Modbus.Net#9]
https://github.com/parallelbgls/Modbus.Net/blob/d5bc2881c9029f54f42d93366382936d37118aff/Modbus.Net/src/Base.Common/TcpConnector.cs#L276

private readonly AsyncLock _mutex = new AsyncLock();
public async Task UseLockAsync()
{
  // AsyncLock can be locked asynchronously
  using (await _mutex.LockAsync())
  {
    // It's safe to await while the lock is held
    await Task.Delay(TimeSpan.FromSeconds(1));
  }
}

**Comment by parallelbgls** [comment]
#7

**Comment by parallelbgls** [comment]
由于TCP和UDP已经修改为DotNetty，这个漏洞不存在了。
串口依然有需要修正的地方。请关注 #7 。
这个Issue关闭。
